"use client";
import { useMemo, useState } from "react";
type Stage="intro"|"memorize"|"switch"|"reveal";
const firstSets=[["K♠","7♥","Q♦","9♣","J♥","K♦"],["Q♠","8♥","K♣","10♦","J♠","Q♥"],["J♦","9♠","K♥","7♣","Q♣","10♥"]];
const secondSets=[["Q♣","8♦","J♠","10♥","K♣"],["J♥","9♣","Q♦","K♠","8♠"],["10♣","K♥","Q♠","J♦","9♥"]];
export default function MissingCardGame(){const[stage,setStage]=useState<Stage>("intro");const[round,setRound]=useState(0);const index=useMemo(()=>round%firstSets.length,[round]);const first=firstSets[index],second=secondSets[index];const restart=()=>{setRound(v=>v+1);setStage("intro")};
return <main className="game-shell illusion-shell"><div className="game-topbar"><a href="/" className="back-button">←</a><span>ไพ่ที่หายไป</span><span className="version-pill">V1.3</span></div>
{stage==="intro"&&<section className="game-panel intro-panel"><div className="mind-orb">🃏</div><p className="eyebrow">ไม่ต้องกดไพ่ที่เลือก</p><h1 className="game-heading">จำไพ่หนึ่งใบไว้ในใจ</h1><div className="rules"><p>เลือกด้วยสายตาเท่านั้น</p><p>อย่าพูดชื่อไพ่</p><p>อย่าจิ้มไพ่ที่คุณจำ</p></div><button className="game-primary" onClick={()=>setStage("memorize")}>เริ่มเกม</button></section>}
{stage==="memorize"&&<section className="game-panel card-stage"><p className="eyebrow">ขั้นที่ 1</p><h1 className="question-title">เลือกและจำไพ่หนึ่งใบ</h1><p className="question-help">จำทั้งตัวเลข/ตัวอักษรและดอกของมันให้ชัด</p><div className="playing-card-grid">{first.map(c=><div className="playing-card" key={c}>{c}</div>)}</div><button className="game-primary inline-action" onClick={()=>setStage("switch")}>ฉันจำแล้ว</button></section>}
{stage==="switch"&&<section className="game-panel center-panel"><div className="reading-orb"><div>🧠</div></div><p className="eyebrow">โฟกัสที่ไพ่ใบนั้น</p><h1 className="reading-title">อย่าเปลี่ยนไพ่ในใจ...</h1><button className="game-primary inline-action" onClick={()=>setStage("reveal")}>พร้อมแล้ว เปิดชุดใหม่</button></section>}
{stage==="reveal"&&<section className="game-panel card-stage"><p className="eyebrow">ขั้นที่ 2</p><h1 className="question-title">ไพ่ที่คุณจำไว้หายไปแล้ว</h1><p className="question-help">ลองหาให้ดีอีกครั้ง</p><div className="playing-card-grid reveal-cards">{second.map(c=><div className="playing-card" key={c}>{c}</div>)}</div><div className="reveal-actions inline-actions"><button className="game-primary" onClick={restart}>😳 เล่นอีกครั้ง</button><a className="ghost-link" href="/games/math-force">เล่นเลขที่หนีไม่พ้น →</a><a className="ghost-link" href="/">กลับหน้าหลัก</a></div></section>}
</main>}
