"use client";
import { useEffect,useState } from "react";
import {clearAdminToken,createAnnouncement,getAdminSnapshot,loginAdmin,toggleAnnouncement,updateFeature,updateGame,updateSite,type AdminSnapshot,type SiteSettings,type AdminGame} from "../lib/adminApi";
const n=new Intl.NumberFormat("th-TH");
export default function AdminPanel(){
 const[snapshot,setSnapshot]=useState<AdminSnapshot|null>(null);
 const[loading,setLoading]=useState(true);
 const[error,setError]=useState("");
 const[email,setEmail]=useState(""); const[password,setPassword]=useState("");
 const[siteDraft,setSiteDraft]=useState<SiteSettings|null>(null);
 const[annTitle,setAnnTitle]=useState(""); const[annBody,setAnnBody]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const s=await getAdminSnapshot();setSnapshot(s);setSiteDraft(s.site)}catch(e){setSnapshot(null);setError(e instanceof Error?e.message:"load_failed")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const login=async()=>{setError("");try{await loginAdmin(email,password);await load()}catch(e){setError(e instanceof Error?e.message:"login_failed")}};
 if(loading&&!snapshot)return <main className="admin-login"><div className="admin-login-card"><h1>MindPlay Admin</h1><p>กำลังตรวจสอบสิทธิ์...</p></div></main>;
 if(!snapshot)return <main className="admin-login"><div className="admin-login-card"><p className="eyebrow">Admin Control Center</p><h1>เข้าสู่ระบบผู้ดูแล</h1><p>บัญชีต้องมีสิทธิ์ <code>app_metadata.role = admin</code> ใน Supabase Auth</p><input placeholder="อีเมล" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/><input placeholder="รหัสผ่าน" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/>{error&&<div className="admin-error">{error==="not_admin"?"บัญชีนี้ไม่มีสิทธิ์ผู้ดูแล":error}</div>}<button onClick={()=>void login()}>เข้าสู่ระบบ</button><a href="/">กลับหน้า MindPlay</a></div></main>;
 const s=snapshot.stats?.summary;
 const saveSite=async()=>{if(!siteDraft)return;await updateSite(siteDraft);await load()};
 const saveGame=async(game:AdminGame,patch:Partial<AdminGame>)=>{await updateGame(game.game_id,patch);await load()};
 return <main className="admin-shell"><aside className="admin-sidebar"><div><strong>MindPlay</strong><span>Control Center V1.9</span></div><nav><a href="#dashboard">Dashboard</a><a href="#website">Website</a><a href="#games">Games</a><a href="#features">Features</a><a href="#announcements">Announcement</a><a href="#audit">Audit Log</a></nav><button onClick={()=>{clearAdminToken();location.reload()}}>ออกจากระบบ</button></aside><section className="admin-content">
 <header className="admin-topbar"><div><p className="eyebrow">MindPlay V1.9</p><h1>Admin Control Center</h1></div><a href="/" target="_blank">เปิดเว็บไซต์</a></header>
 <section id="dashboard" className="admin-section"><div className="admin-section-head"><h2>Dashboard</h2><span>30 วันล่าสุด</span></div><div className="admin-metrics"><article><span>Visitors</span><strong>{n.format(s?.visitors??0)}</strong></article><article><span>Page Views</span><strong>{n.format(s?.page_views??0)}</strong></article><article><span>Game Starts</span><strong>{n.format(s?.game_starts??0)}</strong></article><article><span>Completion</span><strong>{n.format(s?.completion_rate??0)}%</strong></article></div></section>
 <section id="website" className="admin-section"><div className="admin-section-head"><h2>Website Settings</h2><button onClick={()=>void saveSite()}>บันทึกเว็บไซต์</button></div>{siteDraft&&<div className="admin-form-grid"><label>ชื่อเว็บไซต์<input value={siteDraft.site_name} onChange={e=>setSiteDraft({...siteDraft,site_name:e.target.value})}/></label><label className="wide">Hero Title<input value={siteDraft.hero_title} onChange={e=>setSiteDraft({...siteDraft,hero_title:e.target.value})}/></label><label className="wide">Hero Description<textarea value={siteDraft.hero_description} onChange={e=>setSiteDraft({...siteDraft,hero_description:e.target.value})}/></label><label className="toggle-row">Maintenance Mode<input type="checkbox" checked={siteDraft.maintenance_mode} onChange={e=>setSiteDraft({...siteDraft,maintenance_mode:e.target.checked})}/></label><label className="toggle-row">Public Stats<input type="checkbox" checked={siteDraft.public_stats_enabled} onChange={e=>setSiteDraft({...siteDraft,public_stats_enabled:e.target.checked})}/></label><label className="toggle-row">Home Stats<input type="checkbox" checked={siteDraft.home_stats_enabled} onChange={e=>setSiteDraft({...siteDraft,home_stats_enabled:e.target.checked})}/></label><label className="wide">ข้อความ Maintenance<textarea value={siteDraft.maintenance_message} onChange={e=>setSiteDraft({...siteDraft,maintenance_message:e.target.value})}/></label></div>}</section>
 <section id="games" className="admin-section"><div className="admin-section-head"><h2>Game Manager</h2><span>{snapshot.games.length} เกม</span></div><div className="admin-game-list">{snapshot.games.map(game=><article key={game.game_id}><div className="admin-game-main"><div><strong>{game.title}</strong><small>{game.game_id}</small></div><span className={game.enabled?"status-on":"status-off"}>{game.enabled?"เปิด":"ปิด"}</span></div><div className="admin-game-actions"><button onClick={()=>void saveGame(game,{enabled:!game.enabled})}>{game.enabled?"ปิดเกม":"เปิดเกม"}</button><button onClick={()=>void saveGame(game,{maintenance:!game.maintenance})}>{game.maintenance?"ปิด Maintenance":"เปิด Maintenance"}</button><label>ลำดับ<input type="number" value={game.sort_order} onChange={e=>void saveGame(game,{sort_order:Number(e.target.value)})}/></label></div><textarea defaultValue={game.description??""} onBlur={e=>void saveGame(game,{description:e.target.value})}/></article>)}</div></section>
 <section id="features" className="admin-section"><div className="admin-section-head"><h2>Feature Flags</h2></div><div className="admin-flags">{snapshot.flags.map(flag=><label key={flag.key}><span><strong>{flag.key}</strong><small>{flag.description}</small></span><input type="checkbox" checked={flag.enabled} onChange={e=>void updateFeature(flag.key,e.target.checked).then(load)}/></label>)}</div></section>
 <section id="announcements" className="admin-section"><div className="admin-section-head"><h2>Announcement</h2></div><div className="admin-ann-create"><input placeholder="หัวข้อประกาศ" value={annTitle} onChange={e=>setAnnTitle(e.target.value)}/><textarea placeholder="ข้อความประกาศ" value={annBody} onChange={e=>setAnnBody(e.target.value)}/><button onClick={()=>void createAnnouncement(annTitle,annBody,true).then(()=>{setAnnTitle("");setAnnBody("");return load()})}>สร้างประกาศ</button></div><div className="admin-ann-list">{snapshot.announcements.map(item=><article key={item.id}><div><strong>{item.title}</strong><p>{item.body}</p></div><button onClick={()=>void toggleAnnouncement(item.id,!item.enabled).then(load)}>{item.enabled?"ปิด":"เปิด"}</button></article>)}</div></section>
 <section id="audit" className="admin-section"><div className="admin-section-head"><h2>Audit Log</h2><span>30 รายการล่าสุด</span></div><div className="admin-audit">{snapshot.audits.map(log=><article key={log.id}><div><strong>{log.action}</strong><small>{log.target_type}{log.target_id?" • "+log.target_id:""}</small></div><time>{new Date(log.created_at).toLocaleString("th-TH")}</time></article>)}</div></section>
 </section></main>;
}
