"use client";
import { useState } from "react";
type Stage="intro"|"steps"|"reading"|"reveal";
const steps=["คิดเลขอะไรก็ได้ตั้งแต่ 1 ถึง 9","คูณเลขนั้นด้วย 2","บวก 10 เข้าไป","หารผลลัพธ์ด้วย 2","ลบเลขแรกที่คุณคิดไว้ออก"];
export default function MathForceGame(){const[stage,setStage]=useState<Stage>("intro");const[step,setStep]=useState(0);const next=()=>{if(step<steps.length-1)setStep(v=>v+1);else{setStage("reading");window.setTimeout(()=>setStage("reveal"),1400)}};const restart=()=>{setStep(0);setStage("intro")};
if(stage==="intro")return <main className="game-shell force-shell"><div className="game-topbar"><a href="/" className="back-button">←</a><span>เลขที่หนีไม่พ้น</span><span className="version-pill">V1.3</span></div><section className="game-panel intro-panel"><div className="mind-orb">🧠</div><p className="eyebrow">เกมคำนวณในใจ</p><h1 className="game-heading">คุณเป็นคนเลือกเลขเองทั้งหมด</h1><div className="rules"><p>ไม่ต้องกรอกเลข</p><p>ทำตามทีละขั้น</p><p>ใช้เครื่องคิดเลขได้ถ้าต้องการ</p></div><button className="game-primary" onClick={()=>setStage("steps")}>ฉันพร้อมแล้ว</button></section></main>;
if(stage==="steps")return <main className="game-shell force-shell"><div className="game-topbar"><a href="/" className="back-button">←</a><span>เลขที่หนีไม่พ้น</span><span className="step-label">{step+1}/{steps.length}</span></div><section className="game-panel force-stage"><div className="progress-track"><div className="progress-fill" style={{width:`${((step+1)/steps.length)*100}%`}}/></div><p className="eyebrow">ขั้นที่ {step+1}</p><div className="force-step-number">{step+1}</div><h1 className="question-title">{steps[step]}</h1><p className="question-help">ทำในใจให้เสร็จก่อน แล้วค่อยไปขั้นต่อไป</p><button className="game-primary inline-action" onClick={next}>{step===steps.length-1?"ฉันได้คำตอบแล้ว":"ทำเสร็จแล้ว →"}</button></section></main>;
if(stage==="reading")return <main className="game-shell center-stage"><div className="reading-orb"><div>🧠</div></div><p className="eyebrow">คำตอบของคุณถูกล็อกแล้ว</p><h1 className="reading-title">ผมไม่เคยเห็นเลขแรกของคุณ...</h1></main>;
return <main className="game-shell center-stage reveal-stage"><p className="eyebrow">แต่เลขสุดท้ายของคุณคือ</p><div className="reveal-number">5</div><h1 className="reveal-question">ไม่ว่าคุณจะเริ่มจากเลขไหน ผลก็หนีเลขนี้ไม่พ้น</h1><div className="reveal-actions"><button className="game-primary" onClick={restart}>เล่นอีกครั้ง</button><a className="ghost-link" href="/games/missing-card">🃏 ลองเกมไพ่ต่อ</a><a className="ghost-link" href="/">กลับหน้าหลัก</a></div></main>}
