create table if not exists public.visitor_sessions (
  id uuid primary key,
  first_path text not null default '/',
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.game_sessions (
  id uuid primary key default gen_random_uuid(),
  visitor_id uuid not null references public.visitor_sessions(id) on delete cascade,
  game_id text not null check (game_id in ('card-mind','number-mind','symbol-mind','word-mind','sealed-prediction')),
  status text not null default 'active' check (status in ('active','completed','abandoned')),
  token_hash text not null,
  state jsonb not null default '{}'::jsonb,
  result_correct boolean,
  replay_count integer not null default 0 check (replay_count >= 0),
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null references public.visitor_sessions(id) on delete cascade,
  game_session_id uuid references public.game_sessions(id) on delete set null,
  event_type text not null check (event_type in ('page_view','game_view','game_start','game_complete','guess_correct','guess_wrong','game_replay','share')),
  game_id text check (game_id is null or game_id in ('card-mind','number-mind','symbol-mind','word-mind','sealed-prediction')),
  path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.game_configs (
  game_id text primary key check (game_id in ('card-mind','number-mind','symbol-mind','word-mind','sealed-prediction')),
  title text not null,
  enabled boolean not null default true,
  sort_order smallint not null,
  updated_at timestamptz not null default now()
);

insert into public.game_configs (game_id,title,enabled,sort_order) values
 ('card-mind','ไพ่ในความคิด',true,1),
 ('number-mind','เลขที่คุณกำลังคิด',true,2),
 ('symbol-mind','สัญลักษณ์ในใจ',true,3),
 ('word-mind','คำที่ซ่อนอยู่ในหัว',true,4),
 ('sealed-prediction','คำทำนายที่ปิดผนึก',true,5)
on conflict (game_id) do update set title=excluded.title,sort_order=excluded.sort_order,updated_at=now();

create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index if not exists analytics_events_type_created_idx on public.analytics_events (event_type,created_at desc);
create index if not exists analytics_events_game_type_created_idx on public.analytics_events (game_id,event_type,created_at desc) where game_id is not null;
create index if not exists analytics_events_visitor_created_idx on public.analytics_events (visitor_id,created_at desc);
create index if not exists analytics_events_game_session_idx on public.analytics_events (game_session_id) where game_session_id is not null;
create index if not exists game_sessions_visitor_started_idx on public.game_sessions (visitor_id,started_at desc);
create index if not exists game_sessions_game_status_idx on public.game_sessions (game_id,status,started_at desc);

alter table public.visitor_sessions enable row level security;
alter table public.game_sessions enable row level security;
alter table public.analytics_events enable row level security;
alter table public.game_configs enable row level security;

revoke all on table public.visitor_sessions from anon,authenticated;
revoke all on table public.game_sessions from anon,authenticated;
revoke all on table public.analytics_events from anon,authenticated;
revoke all on table public.game_configs from anon,authenticated;
revoke all on sequence public.analytics_events_id_seq from anon,authenticated;

grant select,insert,update,delete on table public.visitor_sessions to service_role;
grant select,insert,update,delete on table public.game_sessions to service_role;
grant select,insert,update,delete on table public.analytics_events to service_role;
grant select,insert,update,delete on table public.game_configs to service_role;
grant usage,select on sequence public.analytics_events_id_seq to service_role;

create policy "deny_public_visitor_sessions" on public.visitor_sessions for all to anon,authenticated using (false) with check (false);
create policy "deny_public_game_sessions" on public.game_sessions for all to anon,authenticated using (false) with check (false);
create policy "deny_public_analytics_events" on public.analytics_events for all to anon,authenticated using (false) with check (false);
create policy "deny_public_game_configs" on public.game_configs for all to anon,authenticated using (false) with check (false);

create or replace function public.get_mindplay_stats(p_days integer default 30)
returns jsonb language sql stable security invoker set search_path=public as $$
with scoped as (
 select * from public.analytics_events
 where p_days=0 or created_at>=now()-make_interval(days=>greatest(1,least(p_days,3650)))
), summary as (
 select
  count(*) filter(where event_type='page_view') page_views,
  count(distinct visitor_id) filter(where event_type='page_view') visitors,
  count(*) filter(where event_type='game_start') game_starts,
  count(*) filter(where event_type='game_complete') game_completions,
  count(*) filter(where event_type='guess_correct') correct_guesses,
  count(*) filter(where event_type='guess_wrong') wrong_guesses,
  count(*) filter(where event_type='game_replay') replays,
  count(*) filter(where event_type='share') shares
 from scoped
), game_stats as (
 select c.game_id,c.title,c.sort_order,
  count(*) filter(where e.event_type='game_start') starts,
  count(*) filter(where e.event_type='game_complete') completions,
  count(*) filter(where e.event_type='guess_correct') correct,
  count(*) filter(where e.event_type='guess_wrong') wrong,
  count(*) filter(where e.event_type='game_replay') replays,
  count(*) filter(where e.event_type='share') shares
 from public.game_configs c left join scoped e on e.game_id=c.game_id
 where c.enabled=true group by c.game_id,c.title,c.sort_order
), daily as (
 select (created_at at time zone 'Asia/Bangkok')::date day,
  count(*) filter(where event_type='page_view') page_views,
  count(distinct visitor_id) filter(where event_type='page_view') visitors,
  count(*) filter(where event_type='game_start') game_starts,
  count(*) filter(where event_type='game_complete') completions
 from scoped group by 1
)
select jsonb_build_object(
 'period_days',p_days,
 'summary',(select jsonb_build_object(
  'page_views',page_views,'visitors',visitors,'game_starts',game_starts,'game_completions',game_completions,
  'correct_guesses',correct_guesses,'wrong_guesses',wrong_guesses,'replays',replays,'shares',shares,
  'completion_rate',case when game_starts=0 then 0 else round((game_completions::numeric/game_starts)*100,1) end,
  'correct_rate',case when(correct_guesses+wrong_guesses)=0 then 0 else round((correct_guesses::numeric/(correct_guesses+wrong_guesses))*100,1) end
 ) from summary),
 'games',coalesce((select jsonb_agg(jsonb_build_object(
  'game_id',game_id,'title',title,'starts',starts,'completions',completions,'correct',correct,'wrong',wrong,'replays',replays,'shares',shares,
  'completion_rate',case when starts=0 then 0 else round((completions::numeric/starts)*100,1) end,
  'correct_rate',case when(correct+wrong)=0 then 0 else round((correct::numeric/(correct+wrong))*100,1) end
 ) order by starts desc,sort_order) from game_stats),'[]'::jsonb),
 'daily',coalesce((select jsonb_agg(jsonb_build_object(
  'day',day,'page_views',page_views,'visitors',visitors,'game_starts',game_starts,'completions',completions
 ) order by day) from daily),'[]'::jsonb),
 'active_now',(select count(*) from public.game_sessions where status='active' and updated_at>=now()-interval '15 minutes')
);
$$;

revoke all on function public.get_mindplay_stats(integer) from public,anon,authenticated;
grant execute on function public.get_mindplay_stats(integer) to service_role;
